### ISSUE TITLE
Bodyslam missing graphics

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1368]
Missing player tiles possibly more, working in mame2000. Looks like the spritesystem is wrong and possibly some of the other configs in the machine driver

Mame2000
![bodyslam-220608-192617](https://user-images.githubusercontent.com/49591133/172733930-11a81dc7-d65e-4ccb-97d0-80d3b3228b65.png)

Mame2003-plus
![bodyslam-220608-192820](https://user-images.githubusercontent.com/49591133/172733995-30dc9876-7f6f-4e2a-93cb-766f2e33eeaa.png)

**Comment by mahoneyt944** [comment]
Changing the sprite system shows improvements, that the sprites are actually there lol, probably just not configured correctly.
![bodyslam-220609-035921](https://user-images.githubusercontent.com/49591133/172796322-57444c1b-798e-497d-aa53-7dd67292f9c3.png)

**Comment by MistyDreams** [comment]
@mahoneyt944 you can use the code anytime its from a new mame just a few banking niggles i want to work out for afighters. I wouldnt recommend this in master atm though really up to you guys though

**Comment by mahoneyt944** [comment]
Just pulled it into a branch called Mist for testing.

**Comment by MistyDreams** [comment]
works fine on mine had a look bankswitch isint working i fixed it on mine a while back https://github.com/MistyDreams/mame2003-plus-libretro/commit/33be9254222fd7dde8e341d76ac2bb6af40c6e8e

**Comment by mahoneyt944** [comment]
Just tried this, it didn't fix the issue, bodyslam isn't setting a obj_bank either.

**Comment by MistyDreams** [comment]
work fine on my port no idea why maybe something else else has chaged

**Comment by mahoneyt944** [comment]
Idk something simple I'm sure but don't see it.

**Comment by MistyDreams** [comment]
I updated to the latest master n my branch compiled it and it works fine

**Comment by mahoneyt944** [comment]
Wtf? With no changes?

**Comment by MistyDreams** [comment]
yeap fine with no changes did you verify your roms?

**Comment by mahoneyt944** [comment]
I believe they are right. Just got another set and tried with no luck. Screen shot yours working

**Comment by mahoneyt944** [comment]
It's the titlescreen where they don't work

**Comment by MistyDreams** [comment]
I dont have any glitches it the title screen is blank
![Screenshot from 2022-06-10 00-31-04](https://user-images.githubusercontent.com/105502489/172961882-b6bc3149-4d8e-4792-a599-d3343c6eaf0e.png)
![Screenshot from 2022-06-10 00-31-14](https://user-images.githubusercontent.com/105502489/172961885-e951d42c-76fa-452f-b78e-7aa18b384a68.png)
![Screenshot from 2022-06-10 00-31-23](https://user-images.githubusercontent.com/105502489/172961886-e9af987c-6c45-4e40-a5f4-bda1ef629756.png)

**Comment by mahoneyt944** [comment]
Where it says coin insert

**Comment by mahoneyt944** [comment]
See the first post

**Comment by MistyDreams** [comment]
yea its missing here but no corruption though :)

**Comment by mahoneyt944** [comment]
Yeah there's no corruption here either, it gets the corruption effect if you change the sprite system, but by doing this shows that the tiles are there.

**Comment by MistyDreams** [comment]
well there is no updateproc

**Comment by MistyDreams** [comment]
I was going to do this at the weekend but i done it now tested and the it fixes the issue
![Screenshot from 2022-06-10 01-35-13](https://user-images.githubusercontent.com/105502489/172967440-6ac0ef76-cbc0-444e-899c-679cff1b0b66.png)

**Comment by MistyDreams** [comment]
ps that copyright warning is only meant to show the first time you load a game not every time!

**Comment by mahoneyt944** [comment]
There's a core option to disable the copyright warning. Shouldn't show at all if disabled.

**Comment by MistyDreams** [comment]
I should get this afigher issue fixed this weekend. Its most likely some kind of banking issue cause the code clamps it

**Comment by MistyDreams** [comment]
im going to delete my opaopa branch soon if you want to grab the fixes for this before i do feel free

**Comment by mahoneyt944** [comment]
I can't recall where we were with this to be honest, I'm currently in the middle of closing on a new house. Not sure when I'll have time to look back.

**Comment by MistyDreams** [comment]
well ill leave the branch open for now till you have time no rush was just cleaning up

**Comment by mahoneyt944** [comment]
Do we want to just create the segas16a driver and video driver instead? Seems you already had the vidhrdw ported. There's not that many games anyway. Plus I'd like to slowly obsolete the system16 driver in favor of the new one. Thoughts?

**Comment by mahoneyt944** [comment]
@MistyDreams ok, had a chance to look through this using the old code and the issue is with the sprite priority. Mame2000 uses variable `spr_pri` differently than we are in mame2003-plus. Looks to be something that wasn't quite converted properly in the change over. This branch isn't correct in the sense it messes up other priorities, but you can see how it displays the title graphics now. so it's definitely where the issue occurs and probably can be fixed with a little adjustment. See the branch:

https://github.com/libretro/mame2003-plus-libretro/compare/Test

**Comment by MistyDreams** [comment]
use this as a reference 

https://github.com/MistyDreams/mame2003-plus-libretro/blob/942f54ef3a47f06bf8c9fd80dc8203a9c5768a3d/src/vidhrdw/system16_vidhrdw.c#L222-L352

also in afighter the boat should go under the road bridges in attract mode sequence hardly a game stopping thing though

**Comment by mahoneyt944** [comment]
Hmm, well if I just remove the `if (spr_pri)` condition it fixes bodyslams title graphics. But i have no idea, if this condition is used by other games. Or perhaps it's an incomplete condition.

**Comment by mahoneyt944** [comment]
Also noticed there's a shift in the rope line. It's off by 1 pixel or something.
![bodyslam-220623-213459_1](https://user-images.githubusercontent.com/49591133/175443671-0fa445c6-82b4-4e9e-a768-611ced7865be.png)

**Comment by MistyDreams** [comment]
Well int sprpri  = 1 << ((source[4] >> 0) & 0x3);  should get your characters back. Again you would need port the rest of the code i posted above or just use it all to draw the sprites for this old system(it works fine on my opaopa branch with the old system). And dont worry about the sprites anymore. 

If you insist on using the old video code youll need to live with the niggles like the rope. Or bring in segas16a up to which one you do is up to you when you get the time. You could fix the spites up with code linked above if you insist on using the old sprite system.

**Comment by mahoneyt944** [comment]
I don't really care which method we use. I was just curious as to why it became broken, being that this game did not have the rope issue or the missing title sprites back in mame2000. Seems like there were many games that suffered from minor regressions between that time and mame2003.

I'm curious as to why spr_pri was used in a if condition here where mame2000 did not. I can't see any improvement from having it, just the regression in bodyslam.

**Comment by mahoneyt944** [comment]
Also updated my PR to move the y sprites one pixel which fixes the rope issue too

**Comment by mahoneyt944** [comment]
Hmm... based on the health bar, the x is also off one pixel, this was also the case in mame2000. There must be an issue somewhere not accounting for this.

**Comment by mahoneyt944** [comment]
Updated PR to fix sprite alignment.

**Comment by MistyDreams** [comment]
Since you can drop in segas16a sprite code or just straight up moved to the segas16a code to fix any tile issues as well. I Dont understand why your trying to patch this like this, but if thats the route you want to take who am i to argue.

**Comment by mahoneyt944** [comment]
I realize the newer sprite code is probably the better solution and I'll be adding that in shortly. I was just curious to the regressions and where things went wrong so long ago. tinkering for fun.

**Comment by mahoneyt944** [comment]
Well funny enough, patching the old sprite code vs the new segas16a sprite code both have this same glitch on the title screen. When she swings, there's a bar of pixels under her arm with some issues....Not sure why. Maybe priority related?
![bodyslam-220624-085124](https://user-images.githubusercontent.com/49591133/175540220-9c26f2b8-60df-4e89-b9c1-5c6217536971.png)

**Comment by MistyDreams** [comment]
what glitch is that the counter being missing ?

**Comment by mahoneyt944** [comment]
Not sure what you're mean about the counter. I'm talking about the title screen under the arm when she swings.

**Comment by mahoneyt944** [comment]
Trying mjleague with the new code, this also has minor issues (so did the old). see the lower corners, the layers aren't in line or something and you get the bars where the background shines through. Most noticable over the green grass. 1 bar above "WT" and 2 bars by the strike count.
![mjleague-220624-091257](https://user-images.githubusercontent.com/49591133/175543797-f4d267e4-2649-447d-9681-6567db3d325d.png)

**Comment by MistyDreams** [comment]
well youll need to tweak the  priorites

**Comment by MistyDreams** [comment]
comment out //	sys16_bg_priority_value=0x0e00; in bodyslam should fix it

**Comment by mahoneyt944** [comment]
Btw, I'm not knocking the code, just documenting issues as I find them so I don't forget. Lol

**Comment by mahoneyt944** [comment]
> comment out // sys16_bg_priority_value=0x0e00; in bodyslam should fix it

I'll try

**Comment by mahoneyt944** [comment]
Well while that does improve the title screen, it's messes up other priorities. When you get tossed out of the ring your player shows through the health bars
![bodyslam-220624-094116](https://user-images.githubusercontent.com/49591133/175548881-3069b1a8-7739-4dfa-a97e-6afa09886174.png)

**Comment by MistyDreams** [comment]
and this is the problem with this video system it can be fixed though youll just need to put the work in

**Comment by MistyDreams** [comment]
I personally think your obsession with fixing this old video code will get you grey hair but in fairness tinker away you will get there.

**Comment by mahoneyt944** [comment]
I'm trying the newer sprite code but I'm not seeing any improvement over just tweaking the old stuff in regards to bodyslam and mjleague. Maybe these things would be fixed if I used all of the newer vidhrdw from segas16a, but I just don't have the time to do it myself right now and test it properly.

**Comment by mahoneyt944** [comment]
mjleague issue is seems to be a y alignment, you can see the right side of the letters where it's split, it it were up a row of pixels it would line up correctly.
![mjleague-220624-091257_1](https://user-images.githubusercontent.com/49591133/175657405-31797e4e-1216-4d20-8058-3ab51cfb7bdd.png)

**Comment by mahoneyt944** [comment]
I don't see it as picky to identify issues and see if they have easy solutions.....isn't that the whole point? Idk... I'm just going to tweak the old code to fix this issue with bodyslam and leave it open for someone else to take it further if they wish.

**Comment by mahoneyt944** [comment]
Just tried current mame, these shadows behind the health bar are present there too. But should they be? Setting fg priority mode 2 prevents the shadows. So we have to decide if we want the shadow or not?

![bodyslam-220624-094116](https://user-images.githubusercontent.com/49591133/175548881-3069b1a8-7739-4dfa-a97e-6afa09886174.png)

**Comment by MistyDreams** [comment]
try fbneo if unsure its anyones guess I assumed you knew it was wrong. Maybe try find some real arcade footage

**Comment by MistyDreams** [comment]
just compiled the latest master sprites are still missing from the title screen

**Comment by MistyDreams** [comment]
ah never mind master was behind n mine. Im going to stop working on  this segas16a till thing quite down here sick of rebasing haha

**Comment by mahoneyt944** [comment]
Oh good 😂 thought there was something else still missing lol. Besides the shadow thing to determine, this game looks good to me now. I think the only true way to know is actual arcade footage but who knows if that's out in the wild or not.

The only other thing I noticed was, in current mame, there's a "curtain raise" effect before the start of the round. Ours just goes right to the match. The effect doesn't look natural to me so I need to see if this effect is suppose to happen or not. I'm guessing it's a y scroll hookup. If it's supposed to do it.

**Comment by mahoneyt944** [comment]
Just tried fbn and there's no shadows, while current mame has shadows. So it's anyone's guess. I think no shadows seems right but idk, no need to worry about that one.

For the curtain thing we are missing it. Probably the yscroll hookup. Here's a pic in the middle of it raising.
![bodyslam-220625-001035](https://user-images.githubusercontent.com/49591133/175757958-bc1ab9a0-7629-4922-826c-faad83ba1bc2.png)

**Comment by MistyDreams** [comment]
its probably the 8751 protection needing done proper like the counter screen being missing too quartet does the same

**Comment by MistyDreams** [comment]
there also priority issues i afighter you might want to look at if you want to fix things, I personal dont feel they are game breaking anyway

**Comment by MistyDreams** [comment]
its also might be worth closing threads for each game and make one system16 bugs thread people can just add to the list that way.
