### ISSUE TITLE
Fix shadows in Golden Axe: The Revenge of Death Adder.

### ISSUE THREAD

**Issue by spielvan** [libretro/mame2003-plus-libretro#407]
In the game Golden Axe · The Revenge of Death Adder occurs a bug in the shadows of the characters, leaving them black with metallic gray and also has a bug when it wins of the head of phase, when it gets to the bonus screens it is bugged as if it had split by half.

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/201

**Comment by markwkidd** [comment]
Yeah, grant is correct that this has been investigated before and can't practically be fixed with the current architecture of the core.

**Comment by arcadez** [comment]
0.97u4: Rewrote the System 32 sprite mixer layer to support accurate implementation of the alpha blending modes. Sprite shadows and several other effects are still not yet implemented. And it's much slower than before [Aaron Giles].

It's fixed by MAME98 although if you read the above the games will take a major hit in the performance
dept, just how much of a hit will depend on which platform your using, however we would need to
change the input code to accept input to port by tagging.

That would be alotta graft however if someone was prepaired to do it i'd backport the driver and
graphical changes.

**Comment by markwkidd** [comment]
Could you say a little more about what tagging input would involve? Or maybe could you tell me where to look at the part of the MAME98 code that would help me get an idea?

**Comment by arcadez** [comment]
Input by tag basically names the input then hooks to it via the input/dip switch tables like so........

static READ16_HANDLER( extra_custom_io_r )
{
	static const char *names[] = { "EXTRA1", "EXTRA2", "EXTRA3", "EXTRA4" };
	switch (offset)
	{
		case 0x20/2:
		case 0x22/2:
		case 0x24/2:
		case 0x26/2:
			return readinputportbytag(names[offset & 3], 0xffff);
	}

	logerror("%06X:unknown extra_custom_io_r(%X) & %04X\n", activecpu_get_pc(), offset*2, mem_mask ^ 0xffff);
	return 0xffff;
}

static INPUT_PORTS_START( ga2 )
	PORT_START_TAG("P1")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_BUTTON1 )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_BUTTON2 )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_BUTTON3 )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY )
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY )
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY )

	PORT_START_TAG("P2")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2 )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2 )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER2 )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_PLAYER2 )
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY | IPF_PLAYER2 )
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_PLAYER2 )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_PLAYER2 )
	
	PORT_START_TAG("PORTC")
	PORT_BIT( 0xff, IP_ACTIVE_LOW, IPT_UNUSED )

	PORT_START_TAG("PORTD")
	PORT_BIT( 0xff, IP_ACTIVE_LOW, IPT_UNUSED )
	
	PORT_START_TAG("SERVICE12")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_SERVICE1 )
	PORT_SERVICE_NO_TOGGLE( 0x02, IP_ACTIVE_LOW )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_COIN1 )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_COIN2 )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_START1 )
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_START2 )
	PORT_BIT( 0xc0, IP_ACTIVE_LOW, IPT_UNKNOWN )

	PORT_START_TAG("EXTRA1")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER3 )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER3 )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER3 )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_UNUSED )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_PLAYER3 )
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY | IPF_PLAYER3 )
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_PLAYER3 )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_PLAYER3 )

	PORT_START_TAG("EXTRA2")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER4 )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER4 )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER4 )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_UNUSED )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_PLAYER4 )
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY | IPF_PLAYER4 )
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_PLAYER4 )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_PLAYER4 )

	PORT_START_TAG("EXTRA3")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_START3 )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_START4 )
	PORT_BIT( 0xfc, IP_ACTIVE_LOW, IPT_UNUSED )
	
	PORT_START_TAG("EXTRA4")

	PORT_START_TAG("SERVICE34")
	PORT_BIT( 0x0f, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_SERVICE3 )	/* sometimes mirrors SERVICE1 */
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_SERVICE4 )	/* tends to also work as a test switch */
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x80, IP_ACTIVE_HIGH, IPT_SPECIAL )	/* EEPROM data */

	PORT_START_TAG("PORTG")
	PORT_BIT( 0xff, IP_ACTIVE_LOW, IPT_UNUSED )

	PORT_START_TAG("PORTH")
	PORT_BIT( 0xff, IP_ACTIVE_LOW, IPT_UNUSED )
INPUT_PORTS_END

**Comment by arcadez** [comment]
I usually removed these and revert the inputs back to MAME78 but for this driver im not sure that
could be done hence i feel we may have to add the tagging support, but there may be some other
obstacles i've not spotted yet.

There may be a way to just keep the older driver but backport the video changes some further
study will be needed.

**Comment by markwkidd** [comment]
Let's keep talking about it. I have some to-dos here in the core but I
might be interested in getting this tagging project written up and on the
list.


That is, if it does turn out to be what we need.

**Comment by grant2258** [comment]
You would need to update every single drivers input code if you changed this. Any reasons we can't just convert the I put to mame 078 format?

**Comment by arcadez** [comment]
Exactly!!! I only mentioned this in the hope it would scare ya's off :) look the graphical problems with
the shadows does make GA RODA look pretty horrible in places and it would be a fix i'd like to do
for this core.

However as mentioned we dont have tagging support for the inputs nor does it look straightforward
to rollback the input code to MAME78, it might be easier infact to try and update the video code
instead.

Keep in mind though when i did this for the Xbox All the Multi and System 32 games dropped from full speed to a little over 5 -10fps stuttery and slow by underclocking the V60 CPU i got em upto just under 20 - 30fps, so half the speed basicially although these games do look lovely with alot of the gfx niggles
they had sorted

In the end i just split up the driver keeping the Multi and System32 games which only had minor
gfx niggles using the older code and GA RODA and the two other games which needed the 
improved graphical handling to function correctly eg Dark Edge and Slip Stream for those
i added the new driver and video and kept them seperate in the core.

But as i said i cant do that for this core easily due to the incompatable input code, nor am i sure
i want to as im winding down with this now being focused a bit more on other projects i have
on the go.

**Comment by grant2258** [comment]
I agree its a big task. For the nec v25  would adding this microcontoller version help with many other games you know of off hand

**Comment by arcadez** [comment]
It might be possible to just use the older protection simulation for GA 2, however to answer your
question some of the Toaplan 2 games which are silent in this core could have full sound and
music if we had the V25 CPU, im struggling to think of anything else off the top of my head
though.

**Comment by arcadez** [comment]
It might be possible to just use the older protection simulation for GA 2, however to answer your
question some of the Toaplan 2 games which are silent in this core could have full sound and
music if we had the V25 CPU, im struggling to think of anything else off the top of my head
though.

**Comment by arcadez2003** [comment]
Alright gonna give this a go no promises it'll pan out or anything but gonna try and splice in the video
code from MAME97 into the older system32 driver while keeping everything else eg inputs eeproms
irq and cpu handling the same.

It's a crazy thing to try but sometime mental things work out :)

**Comment by markwkidd** [comment]
🤯

**Comment by twinaphex** [comment]
That's great to hear, this is definitely a much sought after game.

**Comment by arcadez2003** [comment]
Ok spent the last couple of days looking at this, the video code is so entwined into everything else in
the driver i dont think it's possible to actually update it to get the graphical fixes we require while
still keeping the older system 32 code :(

However all is not lost im going to look at the IO and input code with a view to rolling that back
instead this will be the last roll of the dice

**Comment by arcadez2003** [comment]
> 
> 
> That's great to hear, this is definitely a much sought after game.

Yeah i see the requests to fix it pop up in the chat quite often, if only it was so easy it would have
been done ages ago, it's fully playable but butt ugly in certain areas due to some sprite and shadow
colour mixing problems in the older video code.

MAME78

![ga2780](https://user-images.githubusercontent.com/51386955/60183893-082bb100-981f-11e9-8dca-72c7f7be3ad8.png)

![ga2781](https://user-images.githubusercontent.com/51386955/60183909-0f52bf00-981f-11e9-946c-983fb4c279b8.png)

MAME98 

![ga2980](https://user-images.githubusercontent.com/51386955/60183944-1b3e8100-981f-11e9-9812-0f6b63b23ffe.png)

![ga2981](https://user-images.githubusercontent.com/51386955/60183955-1ed20800-981f-11e9-9cec-a19d13eb3c56.png)

**Comment by spielvan** [comment]
> > That's great to hear, this is definitely a much sought after game.
> 
> Yeah i see the requests to fix it pop up in the chat quite often, if only it was so easy it would have
> been done ages ago, it's fully playable but butt ugly in certain areas due to some sprite and shadow
> colour mixing problems in the older video code.
> 
> MAME78
> 
> ![ga2780](https://user-images.githubusercontent.com/51386955/60183893-082bb100-981f-11e9-8dca-72c7f7be3ad8.png)
> 
> ![ga2781](https://user-images.githubusercontent.com/51386955/60183909-0f52bf00-981f-11e9-946c-983fb4c279b8.png)
> 
> MAME98
> 
> ![ga2980](https://user-images.githubusercontent.com/51386955/60183944-1b3e8100-981f-11e9-9812-0f6b63b23ffe.png)
> 
> ![ga2981](https://user-images.githubusercontent.com/51386955/60183955-1ed20800-981f-11e9-9cec-a19d13eb3c56.png)

 Another game that almost works perfect is the Star Blabe from Namco, so the start when the smaller ship leaves the station in the 2003 mame plus does not appear the station is the direct ship in space.

**Comment by arcadez2003** [comment]
Alright i gave it a go, well two goes but no joy im afraid :(

**Comment by srk15372** [comment]
Hi, sorry to bump this thread but is there any new fix for this game.
?
Would be so fun to play it on mame2003plus without to use another versio   thanks

**Comment by mahoneyt944** [comment]
Fixed the background issues https://github.com/libretro/mame2003-plus-libretro/commit/77826515fb8ebdd02e977f2359d972d80c544cb1

Moving the color issues to #1587 and closing this here.

**Comment by markwkidd** [comment]
Nice!

**Comment by srk15372** [comment]
hi, marvelous

thank you so much
